version: '3.7'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: eventsProject
    ports:
      - "3306:3306"
  app:
    build: .
    ports:
      - "8090:8090"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/eventsProject
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: